### ISSUE TITLE
Deployment and Environement variables

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-docs#11]
Hi,

I deployed oTree to my Debian VM with `apache2` and this was fairly straight forward.  I wrote some step by step instructions, if that's useful.

However, I'm confused about some of the environment variables and parts of `settings.py`.

- `OTREE_PRODUCTION`:  From the `settings.py` it seems this variable controls whether debug info is shown.
- `IS_OTREE_DOT_ORG`:  Do I need to care about this variable at all?
- `OTREE_ADMIN_PASSWORD`, `OTREE_SECRET_KEY`: Looks like variables I should care about, but not in manual.  What's the difference between KEY and PASSWORD?
- `OTREE_AUTH_LEVEL`: In the manual, I'm told to set it to `DEMO` when I want to use my server for production....  What does it do?
- `ACCESS_CODE_FOR_DEFAULT_SESSION`: What exactly is the purpose of this variable?  Is that what users have to put in?
- On database setup: you mention complicated stuff on PostgreSQL.  When I downloaded my copy of `oTree.git` I got something like the following, which Just Work™.  Reading the manual, I don't understand if I have to dig further into setting up databases, or whether the default setup is fine.
```
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'))}
```

Edit: The point of this issue is of course, that I think it would be helpful to have slightly better documentation on the deployment step.

**Comment by oTree-org** [comment]
I added comments directly to settings.py:

https://github.com/oTree-org/oTree/blob/master/settings.py

Later I will add more to the docs, but this should cover the relevant info for now.

Regarding databases: you need to set `DATABASE_URL`, or else your server will default to using SQLite, which is not advisable for production sites.
