### ISSUE TITLE
formfield and loop example with label depending on forloop.counter

### ISSUE THREAD

**Issue by vanderlindenma** [oTree-org/otree-docs#13]
This is somewhat of a follow up question on https://github.com/oTree-org/otree-docs/issues/2.

The answer to https://github.com/oTree-org/otree-docs/issues/2 is very helpful and would definitely be worth adding to the doc.

Along the same lines, it would be nice if the doc explained how to have the forms' labels depend on the forloop.counter. I have tried using what I thought was a standard construct in Django template, namely

`{% for field in form %}

{% formfield field with label="blablabla {{ forloop.counter }}" %}

{% endfor %}`

but got {{forloop.counter}}  appears as is in the label, instead of it being replaced by its value.

Also posted a question at http://stackoverflow.com/questions/32615979/parsing-forloop-counter-in-forms-label-in-django and tried the suggestion there got an error:

Could not parse the remainder: 's" }}?"' from '"blablabla {{ forloop.counter|stringformat:"s" }}?"' (Request Method: GET, Exception Type: TemplateSyntaxError, Django Version: 1.8.4)

Weirdly enough, the person who answered on Stackoverflow was not able to reproduce the error on his machine.

**Comment by oTree-org** [comment]
As discussed over email, I recommend setting `verbose_name` on the model field.
