### ISSUE TITLE
mention how to debug errors in runproductionserver

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-docs#17]
hi,

I get a funny 500 error when I try to initialize a new session under gunicorn.  It's not there when I use the developer server.  Nothing useful is printed to `stdout`, perhaps because the error happens with a worker.
Perhaps the default Procfile should log to some file?  Or perhaps the documentation should mention how to debug errors with gunicorn.

This is not the most structured bug; sorry.

Thanks,

**Comment by leliel12** [comment]
this is **Django/WSGI limitation**, please check: http://stackoverflow.com/questions/238081/how-do-you-log-server-errors-on-django-sites

Also the **correct** way to check bugs on production is by using **sentry**: http://otree.readthedocs.org/en/latest/server.html#sen
