### ISSUE TITLE
postgresql notes

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-docs#18]
Hi,

The notes on how to get `otree` to work with a "proper" sql server are a bit confusing if one is not acquainted with web deployment (and indeed I failed when I tried to follow them).  Also, I'm not sure it's good to use the `postgresql` user for the database. 

Since most social scientists are probably not terribly invested in server deployment it might be nice with some more hand-holding.

I did the following (on `wheezy`),

    $ aptitude install postgresql postgresql-contrib
    $ sudo su - postgres
    $ createuser -P
    Enter name of role to add: otree_db
    Enter password for new role: 
    Enter it again: 
    Shall the new role be a superuser? (y/n) n
    Shall the new role be allowed to create databases? (y/n) n
    Shall the new role be allowed to create more new roles? (y/n) n

In the `settings.py` I used,

    if gethostname().lower() == 'remote':
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': 'otree_data',
                'USER': 'otree_db',
                'PASSWORD': 'psk',
                'HOST': 'localhost',
                'PORT': ''}}
    else:
        DATABASES = {
            'default': dj_database_url.config(
                default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'))}

 the database is then synced with `otree syncdb` and my update script calls `su - postgres -c "dropdb otree_data ; createdb otree_data"`.

Rasmus

**Comment by leliel12** [comment]
http://otree.readthedocs.org/en/latest/server.html#database <<< the documentation is here

also Made the creation of  experiment easy for the scientis is the goal of oTree not configuration of the production level databases. Sadly this need to be done by a proper sysadmin o (if you want) use some **easy-to-deploy** server like [heroku](http://heroku.com). The deployment recipe for heroku is here http://otree.readthedocs.org/en/latest/server.html#heroku
