### ISSUE TITLE
formfield and loop example

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-docs#2]
Hi,

I would appreciate an example on how to combine `{ %for ...}` loops and `{% formfield ...}`.  

In my case I'm trying to do the following.

1. In `views.py` I have `get_form_fields` which dynamically makes a list of fields to modify in the Player table based on the current round and total rounds.  In addition I create a list of lists in `vars_for_template` with contains *string names* of the fields I want to modify plus other stuff.  Called it `fields`: 
```
fields = [[int-a-ID, 'form_field_a1', 'form_field_a2']' [int-b-ID2, 'form_field_b1', 'form_field_b2']]
```

2. In my django html file I want to to add an input box for each element.  I tried something like 

```
{% for id, left, right in fields %}
<div class="panel-row">
  <div class="col-md-4">
    {{ id }}
  </div>
  <div class="col-md-4">
    {% formfield {{ left }} with label="" %}
  </div>
  <div class="col-md-4">
    {% formfield {{ righ }} with label="" %}
  </div>
</div>
{% endfor %}
```

This produces an error, where the backtrace contains
```
django.template.base.TemplateSyntaxError: formfield's second argument must be 'with'.
```
suggesting some sort of escaping is needed.

In general I don't understand *how* fields in e.g. the player table work together with `view.py`.  I mean, I set a table and a list of fields.  Some magic happens, and I end up (hopefully) populating the right field.  But I only gave a string, not an actual field...

Further, when I search for `django` and  `%formfield` I don't find much documentation.  Is it relying on some 3rd party packages?  E.g. someone must surely have had the problem of escaping such fields before, but I simply don't know the vocabulary needed to inform myself.

Thanks,
Rasmus

PS: Is there a (gmane-enabled) mailing list or IRC?

**Comment by oTree-org** [comment]
1) This worked the last time I tested it:

```
{% for field in form %}
    {% formfield field %}
{% endfor %}
```

2) Are you asking about `form_fields`? This comes from Django class-based views (in Django they are called `model` and `fields` whereas oTree calls them `form_model` and `form_fields`. 

For more info, see http://django-vanilla-views.org/api/model-views

3) `formfield` is only found in oTree. It's a simplified and customized version of the Django-floppyforms formrow element.

Thanks for raising these issues, i will update the docs.

**Comment by oTree-org** [comment]
4) I am planning on setting up a mailing list soon. There is an IRC #otree although we have not used it yet. For now, feel free to log issues here or email me at chris@otree.org.

**Comment by pank** [comment]
Re 1: 

To clarify, is `form` a list of **strings** like in my case?  Or did you somehow generated a list of whatever is the object type of a normal field?

Your loop is basically the one I run as well:
```
{% for field in form %}
    {% formfield field %}
{% endfor %}
```
where `form` is a list of strings, and field has either the form `player.my_field` or `my_field`.

When I run this I get a Django Yellow Page of Death with:
> The given variable 'Left'' ('my_field'') is neither a model field nor a form field. (same when I prefix with `player.`.

`player.my_field` exists in `model.py`.

Re 2:  OK, I will try to learn about that as necessary.
Re 3: OK. 

Re 4:Please enable it in `gmane.org` when it's up.  For the nntp crowd.

**Comment by oTree-org** [comment]
`form` is a variable automatically passed to the template. It is a Django form object, which is an iterable whose elements are Django form field objects (not strings). 

https://docs.djangoproject.com/en/1.8/topics/forms/#looping-over-the-form-s-fields

 formfield can take as an argument a Django field object, or it can be an expression like `{% formfield player.foo %}` and {`% formfield group.foo %}`, but `player.foo` must be written as a literal rather than assigning `somevar = player.foo` and then doing `{% formfield somevar %}`.

**Comment by pank** [comment]
```
{% for field in form %}
    {% formfield field %}
{% endfor %}
```
works great.

It should be mentioned explicitly in the otree manual imo, including the fact that the order is the one given by `get_form_fields`.

I will try to write some patches for the manual eventually, including this one (feel free to beat me to it).
