### ISSUE TITLE
How to change values (like payoff matrix of PD) before experiments begin.

### ISSUE THREAD

**Issue by itsaquestion** [oTree-org/otree-docs#23]
Hi! Is there any way to change some values before session begin in the control panel? 
eg. Change the payoff matrix so I can play some different version of PD experiments without creating new app.

Thanks!

**Comment by oTree-org** [comment]
You can use this technique, putting parameters in the session config:

http://otree.readthedocs.io/en/latest/treatments.html#choosing-which-treatment-to-play

That means you don't have to create a whole new app, but you do need to modify the source code.

**Comment by itsaquestion** [comment]
Got it. Thanks.
