### ISSUE TITLE
loading pictures

### ISSUE THREAD

**Issue by nikolassch** [oTree-org/otree-docs#27]
Hi,

I am new to otree and I would like some help on importing graphics.

I followed the documentation creating a static folder and so on.
In the top of my template I included the line 
'{% load staticfiles otree_tags %}'
However, this gives me an unresolved library 'staticfiles'
Subsequently loading the html the picture fails to load.

Can someone explain me what I did wrong?

**Comment by oTree-org** [comment]
If you are talking about the yellow highlight in PyCharm, that can be ignored.

Can you post your template code? Or better yet, post attach the whole app as a .zip (you can drag and drop files into this comment thread)

**Comment by nikolassch** [comment]
Hi,
Thanks for the quick reply!
Attached is the app. I tried to include a picture in the NewsFeed template (I also tried other templates with no success)

Best, Niko

[likes.zip](https://github.com/oTree-org/otree-docs/files/611938/likes.zip)

**Comment by oTree-org** [comment]
Your template references like_button.png, but I only see like_button.jpg.

**Comment by nikolassch** [comment]
You are absolutely right. Now it works... I don't know what I did wrong the whole time (I even met up with the IT guy of our department and he also could not solve it). 
Well I am very happy that it works now and thanks again for the quick answers!
