### ISSUE TITLE
save not submitted variables

### ISSUE THREAD

**Issue by nikolassch** [oTree-org/otree-docs#28]
Hello,

Could somebody explain me how I can define that in case of timeout, whatever was written in an input is stored into that variable?

From the documentation I understood that under
``` python
timeout_submission = {'accept': True}
```
I can define the value of a variable. However, here I do not see how I can access what was the preliminary input.

On the other hand, in the following I accessed the preliminary input, yet there I do not see how to save this under time_out submission since it is inside a function (I tried to write it in `self.player.field` but nothing happens so it seems to be incorrect).
``` python
   def before_next_page(self):

        post_dict = self.request.POST.dict()
        for field in self.form_fields:
            self.player.field = post_dict[field]
```
Is there a straightforward way to do this?

**Comment by oTree-org** [comment]
Hi, I started a discussion about this on the mailing list; let's continue it there. https://groups.google.com/forum/#!topic/otree/bv4fyL00LxE
