### ISSUE TITLE
Talk about buttons

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-docs#3]
Hi,

It would be good with an example on how to make a toggle button.  I spend _hours_ trying to get the darn checkbox inlined until it occured to me that a button was better.

However, I ended up hard-coding it in my template html file with something like:

```
            <button type="button" class="btn btn-default"
                    id="toggle_buy">Buy</button>
```

and a JS function

```
  // script to show/ hide the order fields, based on order type
  function toggle_display(button, label) {
      invisible = "invisible";
      color = "btn-primary";
      button.classList.toggle(color);
      e = document.getElementById(label);
      if (!e.classList.contains(invisible)){
          inputs = e.getElementsByTagName("input")
          for (input of inputs) {input.value = 0}}
      e.classList.toggle(invisible);}

  $(document).ready(function(){

  // Toggle buy box
  document.getElementById('toggle_buy').onclick = function() {
  toggle_display(this, "buyform")};
  })
```

This seems like something that would be quite common in an experiment...?  So I think an example is appropriate for the manual.  Or perhaps even a custom widget type, but I don't know how easy it is to generalize.

**Edit**: better version of script.  Bootstrap `invisible` class is easier and better than display.

**Comment by oTree-org** [comment]
Thanks, I will think about this.
