### ISSUE TITLE
Missing information on oTree Studio pricing

### ISSUE THREAD

**Issue by peterjc** [oTree-org/otree-docs#38]
I note https://otree.readthedocs.io/en/latest/studio.html says:

> [oTree Studio](https://www.otreehub.com/studio) is a point-and-click interface for building oTree apps.
>
> We recommend for new users to start with oTree Studio instead of a text editor (like PyCharm), because it has makes learning oTree much easier and has a free 30-day trial.

The site itself has nothing about pricing, just login and register links - even the top level [oTree Hub](https://www.otreehub.com/) page says just:

 > # oTree Hub
> oTree Hub is the central place to build, launch, and monitor your oTree experiments.
>
> * Design your experiment in oTree Studio, a visual interface for building oTree apps.
> * Deploy and manage oTree servers on Heroku
> * Browse public oTree projects

What is the pricing model, and could the documentation point at this information please?

**Comment by oTree-org** [comment]
Thanks for the feedback, you are right the pricing info should be on the home page. I have been planning to make a proper landing page for oTree Hub, so will try to add this info soon.

**Comment by peterjc** [comment]
Could you post the pricing here or on the Google Group in the short term? This would be very helpful for a grant proposal a colleague is working on.

**Comment by peterjc** [comment]
The site has been updated and https://otree.readthedocs.io/en/latest/studio.html now says:

> oTree Studio is a point-and-click interface for building oTree apps. It is free to use for small/medium sized projects.
>
> We recommend using oTree Studio instead of a text editor (like PyCharm), because it has makes learning oTree much easier and prevents many common mistakes.
>
> Here are some YouTube videos about oTree Studio.

Thanks!
