### ISSUE TITLE
Add example of how to add columns dynamically to group and player

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-docs#4]
The manual talks about how to add fields that a particular view dynamically.

However, it would also be great to be able to add columns to e.g. the `Player` table dynamically.

E.g. I have something like this, which is asking for trouble.
```
    f1  = models.CurrencyField(initial=None, blank = True)
    ⋮
    f30  = models.CurrencyField(initial=None, blank = True)
```

E.g. is there something like a user "`self.assign`" for `otree.models.BasePlayer`?

**Comment by oTree-org** [comment]
We don't have that currently built in, but it might be possible for you to extend oTree to add a separate model with a ForeignKey and then use a formset. However, that might be more complex than having the 30 fields. Happy to discuss on the mailing list/email.

**Comment by pank** [comment]
oTree-org <notifications@github.com> writes:

> We don't have that currently built in, but it might be possible for
> you to extend oTree to add a separate model with a ForeignKey and then
> use a formset. However, that might be more complex than having the 30
> fields. Happy to discuss on the mailing list/email.

OK.  Then it's definitely not a documentation bug.

We can take in on the ML if necessary.

Rasmus

-- 
May contains speling mistake
