### ISSUE TITLE
Randomizing page sequence via rounds link broken

### ISSUE THREAD

**Issue by mcashm** [oTree-org/otree-docs#40]
https://github.com/oTree-org/otree-snippets/tree/master/random_page_order does not work.

The link appears on https://otree.readthedocs.io/en/latest/pages.html#randomizing-page-sequence

**Comment by oTree-org** [comment]
Thanks for reporting! I've fixed it locally. The proper link is here: https://www.otreehub.com/projects/otree-snippets/
