### ISSUE TITLE
Translating experiment to other language

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-docs#5]
Hi,

The [oTree paper pp. 10](http://www.otree.org/oTree.pdf) mentions localization.  Yet I don't see any information on how to actually do this in the manual (I searched for `localization`, `local` and `translate` but didn't see anything immediately useful).  A short introduction to this, or at least a link to the corresponding django documentation should be part of the manual imo.

Rasmus

**Comment by leliel12** [comment]
https://docs.djangoproject.com/en/1.8/topics/i18n/translation/ <<< the translation is part of django

**Comment by pank** [comment]
Juan BC <notifications@github.com> writes:

> Closed #5.

Unless you added the link to the manual I fail to see how a link on an
issue on some website on the interwebs is a solution.

My conjecture is that Social Scientists, whom this software is supposedly
targeted, do not know what "Django" is (and frankly 95%, if not 99%, don't
care).  We would prefer to design our experiments in LaTeX or Word if we
could, even if such tools are highly inappropriate.  Making assumption on
the background knowledge of Django, at least among this group of users,
seems like a mistake IMHO.

Since the feature is advertised in the overview paper, it should be
documented in the manual...  Or removed from the paper.

—Rasmus

**Comment by pank** [comment]
Rasmus Pank Roulund <github@pank.eu> writes:

> Unless you added the link to the manual I fail to see how a link on an
> issue on some website on the interwebs is a solution.
>
> My conjecture is that Social Scientists, whom this software is supposedly
> targeted, do not know what "Django" is (and frankly 95%, if not 99%, don't
> care).  We would prefer to design our experiments in LaTeX or Word if we
> could, even if such tools are highly inappropriate.  Making assumption on
> the background knowledge of Django, at least among this group of users,
> seems like a mistake IMHO.
>
> Since the feature is advertised in the overview paper, it should be
> documented in the manual...  Or removed from the paper.

Juan: My apology, I think the *tone* of the above came off rather bitter.
This is, undoubtedly, not fair.  Sorry.


-- 
⠠⠵
