### ISSUE TITLE
Improve Highchart documentation

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-docs#6]
Hi,

The highchart section does not even mention that high chart is how to add graphics to oTree.  It should at the very least repeat the blob on page 10 of the oTree.pdf paper.

~~I will try to improve this section later, as I need to learn about graphing anyway.~~ [I won't be using Highchart cf. next post].

Rasmus

**Comment by pank** [comment]
Speaking of which, **the [restrictive license](http://shop.highsoft.com/highcharts.html) of highchart** absolutely should be mentioned in the documentation, preferably in a big, fat box.

Note that the FAQ specify:
> A student, university or a public school [can use highchart for free]
> ...
>  Governmental entities are not covered by the non-commercial license. 

Where does that leave government-sponsored universities?
 
Aside: at this point, I'm confused why you'd choose Highchart over `d3.js` or indeed the HTML5 backend of `matplotlib`, given the nasty licenses of highchart (irrespective of whether you adhere to "open source", "free software" or "free lunch").

**Comment by leliel12** [comment]
The discusions of d3 and matplotlib can be in the mailing list or sugest a change on otree-core issues.

Also here we have 2 diferent issues one is about expand hcharts documentation and other about hightchart license. Can you please create another issue for the license topic or send an email to the mailing list for take a discussion in a more confortable way
