### ISSUE TITLE
Improve KaTeX documentation

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-docs#7]
Hi,

At the very least the manual should mention is how to change the font type and size in KaTeX, as CM is usually not a good choice (bootstrap on my computer seems to default to a sans serif font).
It think it needs to be documented in the oTree manual as KaTeX is not as widely used as MathJax, and since the KaTeX manual isn't great (compared to MathJax at least).

As I need to solve this anyway, I'll look into it.  But feel free to beat me to it.

Rasmus

**Comment by leliel12** [comment]
Its only one line of configuration. In the conf.py in extension you need to
remove mathpng (i dnt remember the exact name) and add mathjax

El jue, jun 4, 2015 08:50, pank <notifications@github.com> escribió:

> Hi,
>
> At the very least the manual should mention is how to change the font type
> and size in KaTeX, as CM is usually not a good choice (bootstrap on my
> computer seems to default to a sans serif font).
> It think it needs to be documented in the oTree manual as KaTeX is not as
> widely used as MathJax, and since the KaTeX manual isn't great (compared to
> MathJax at least).
>
> As I need to solve this anyway, I'll look into it. But feel free to beat
> me to it.
>
> Rasmus
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-docs/issues/7>.
>
-- 

Juan BC (from phone)

**Comment by pank** [comment]
I'm not at a computer, but I don't think this is obvious from the manual. Hence the bug report.

**Comment by leliel12** [comment]
This is not for the manual, this is about a configuration how we built the
docs.

On Thu, 4 Jun 2015 at 10:59 pank <notifications@github.com> wrote:

> I'm not at a computer, but I don't think this is obvious from the manual.
> Hence the bug report.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-docs/issues/7#issuecomment-108907756>.
>
-- 

Juan BC (from phone)

**Comment by pank** [comment]
I don't care how the manual is built.

This is about how my experiment looks when I use the latex class as recommended by the manual. Which I understand relies on katex. Since katex doesn't look nice out of the box in the typical otree setting and since it's not so nicely documented, the otree manual should mention the most basic settings imo. So either we are disagreeing or we are talking about different things....

**Comment by oTree-org** [comment]
Yes I think you are talking about different things.

Yes we can expand the docs on using KaTeX. I will also see if we can make a better default look.
