### ISSUE TITLE
Something is wrong with the stylesheet on readmydoc

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-docs#8]
This is what the `readmydoc` manual looks like when my screen is constrained to half of my screen (== 720px).  This is using Firefox.  It looks fine when it can use the entire width (1440px).

![screenshot](http://i.imgur.com/2KtwQ2s.png)

**Comment by oTree-org** [comment]
Yes I also see that on my iPhone/iPad.

**Comment by pank** [comment]
oTree-org <notifications@github.com> writes:

> Yes I also see that on my iPhone/iPad.

Good idea.  I checked with my Android phone (old Moto g) with Firefox.
There the issue is also present.

-- 
Bang bang

**Comment by leliel12** [comment]
i can't reproduce the issue: example(

Pleasse press `<ctrl> + <0>` and/or `<ctrl> + <F5>`

**Comment by leliel12** [comment]
We don't touch the default *Read The Docs* CSS template and also  the image are defined as this substitution https://github.com/oTree-org/otree-docs/blob/master/source/conf.py (line 325)

and the image itself is really small https://github.com/oTree-org/otree-docs/blob/master/source/_static/assets/github-icon.png

**Comment by pank** [comment]
> i can't reproduce the issue: example(http://awesomescreenshot.com/0434zv33a8)

You window is too wide....  `exiftool` tells me the width of your png is 1352px.  Try [responsive design mode](https://github.com/oTree-org/otree-docs/issues/8#issuecomment-113260381), shortcut: <kbd>Ctrl</kbd> <kbd>Meta</kbd> <kbd>a</kbd>.  As you will find it breaks at 769px.

**Comment by gregmuellegger** [comment]
That's probably because of the CSS of readthedocs. They try to make the docs responsive and in most cases it's good that img scale to 100% width on small screens if they are content images (showing graphs for example). But in this case it's more of an icon. Maybe add some custom CSS for those icons to force them in beeing icon size, or otherwise file a bug in the readthedocs.org repo: https://github.com/rtfd/readthedocs.org/issues

**Comment by pank** [comment]
Does it need to be an image at all?  The [readthedoc manual](http://gscontentcss.readthedocs.org/en/latest/icons.html) uses custom glyphs for icons.  They also have github icon which is called like:
```
<a href="https://github.com/groupserver/gs.content.css/blob/master/docs/icons.rst"
   class="fa fa-github">
  Edit on GitHub
</a>
```
