### ISSUE TITLE
Typo "beginneng" in otree-snippets

### ISSUE THREAD

**Issue by peterjc** [oTree-org/otree-docs#96]
Not sure where to report this, since otree-snippets does not seem to be on GitHub (which would have let me submit this as a pull request). Anyway..

The typo "beginneng" appears twice on this page: https://www.otreehub.com/code/

```python
class Transaction(ExtraModel):
    group = models.Link(Group)
    buyer = models.Link(Player)
    seller = models.Link(Player)
    price = models.CurrencyField()
    seconds = models.IntegerField(doc="Timestamp (seconds since beginneng of trading)")
```

**Comment by oTree-org** [comment]
fixed, thanks!

**Comment by peterjc** [comment]
It looks to me like you fixed only one of the two appearances?
